site_name: oncoexporter

theme:
  name: "material"
  features:
    #- navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: white


nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Workplan: 'workplan.md'
  - API:
    - cda:
      - cda_table_importer: 'cda/cda_table_importer.md'
      - cda_individual_factory: 'cda/cda_individual_factory.md'
      - cda_disease: 'cda/cda_disease.md'
    - model:
      - "overview": "index.md"
      - "op_individual": "model/op_individual.md"


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx




markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg



